### ISSUE TITLE
GPT-4, Error : HTTP ERROR: 404

### ISSUE THREAD

**Issue by abhilash-malkar** [IvanCampos/OpenAI-API#1]
POST https://api.openai.com/v1/chat/completions 404        gpt4-api.js:130
HTTP ERROR: 404                                                                   gpt4-api.js:144

Output:
HTTP ERROR: 404

**Comment by IvanCampos** [comment]
This will only work if your OpenAI Account (API Key) has been invited to use the GPT-4 API
